### ISSUE TITLE
[bmi160.h] Incorrect defined BMI160_COM_C_TRIM_FIVE_ADDR value

### ISSUE THREAD

**Issue by trevorbunker** [BoschSensortec/BMI160_driver#1]
According to BST-BMI160-AN0000-02 page 9, you are supposed to write the pullup register settings to address 0x05 (since you have now moved the page). However, the value for BMI160_COM_C_TRIM_FIVE_ADDR in bmi160.h, line 701 is set 0x85. Therefore, the pullup for the SDA pin is never getting set and it stays low.

Also, in bmi160.c you are setting the new pullup value with this bitwise OR:

v_pull_value_u8 = v_pull_value_u8 | BMI160_HEX_0_3_DATA;

However, that same application note says to write 0x10, which would be BMI160_HEX_0_2_DATA

It seems to work with 0x3, but it is a mismatch between the driver and the app note.

**Comment by BoschSensortec** [comment]
1. 0x05 and 0x85 are both correct and can be used to setting the pull up registers. 
2. BMI160_HEX_0_3_DATA and BMI160_HEX_0_2_DATA is represent for different pull up register values.  Depending on the different HW platform, you can choose the suitable one to be used.

**Comment by bobatsar** [comment]
0x85 makes problems if the BMI160 is used with a primary SPI interface as address 0x85 would be read address 0x05 with SPI (bit 0 is read/write bit).

In your code you are changing the page and setting the pullup and so on but this is not documented in the datasheet. Where can that information be found?

**Comment by BoschSensortec** [comment]
We are putting these information into one application notes.   This document will be released soon. 

I tried directly on the sensor.  The page setting are used for SPI tolerance.  So after I switch the page, 0x85 is doing exactly when use 0x05.

**Comment by trevorbunker** [comment]
Except address 0x85 is a read command so you have to mask the MSB.

**Comment by BoschSensortec** [comment]
We will fix it in next version. 
The detail information is put into on application notes and will be released soon.

**Comment by BoschSensortec** [comment]
Thanks for your comments. 
Since there will be no internal pull up registers in BMI160, the related codes will be removed and AN will be phased out. 
Please add external pull up register in your design. For further help, contact the FAE of BoschSensortec.
