### ISSUE TITLE
Incorrect handling of API bmi160_read_fifo_header_data_user_defined_length

### ISSUE THREAD

**Issue by manojrti** [BoschSensortec/BMI160_driver#1]
The reading of bmi160_read_fifo_header_data_user_defined_length is not correctly handled.  Overreading of the fifo can lead to reset of the sytem.

**Comment by BoschSensortec** [comment]
Thank you for your feedback. We will look into this.

**Comment by BoschSensortec** [comment]
@manojrti ,

This is fixed in the latest release.
