### ISSUE TITLE
Wrong Comparison 

### ISSUE THREAD

**Issue by kg3DtHFb1J802J1Ut** [BoschSensortec/BMI160_driver#13]
According to the comment, the previous state should be compared to the current state:
dev->gyro_cfg.power  should be used, or?

https://github.com/BoschSensortec/BMI160_driver/blob/e69b9472c2a49300fd86325f374ce0c467a64792/bmi160.c#L3076

**Comment by BoschSensortec** [comment]
@kg3DtHFb1J802J1Ut ,

Yes it is a typo. This will be corrected in the next release.

Thank you.

**Comment by BoschSensortec** [comment]
@kg3DtHFb1J802J1Ut ,
Fixed in the release 3.7.2
