### ISSUE TITLE
In I2C mode , how can I use int1 to realize step counter,use int2 to realize flat Interrupt?

### ISSUE THREAD

**Issue by ouki-wang** [BoschSensortec/BMI160_driver#21]
When use int1 to realize step counter, the first seven datas of the step counter are 0, and the eight number data  back to normal.
When use int2 to realize step counter,  the first seven datas of the step counter also are 0, but from the eight number data, it returns ≥ 2 data and these datas are mainly wrong. Could you please help to finger it out, why?
What's more ,what's the diffrence between int1 and int2 ? Can int1 and int2 work in I2C mode simultaneously?

**Comment by BoschSensortec** [comment]
Hi @ouki-wang,

The step counter algorithm doesn't recognize steps until at least 7 steps continuously are observed. Note that these 'starting' steps should occur within a small duration and hence if you were to stop in between of these 7 steps for too long, the counter resets. 

There is no difference between INT1 and INT2. Both should work the same way in this context and also in the I2C or SPI mode.
