### ISSUE TITLE
Invalid operation when using #define MACHINE_16_BIT

### ISSUE THREAD

**Issue by xioTechnologies** [BoschSensortec/BMI160_driver#3]
The compiler outputs the following warning when MACHINE_16_BIT is used i place of MACHINE_32_BIT.

bmi160.c:16828:4: warning: left shift count >= width of type

I presume this results in faulty behavior but I have not tested it.

**Comment by BoschSensortec** [comment]
@xioTechnologies 

We look into this and resolve it at the earliest.

**Comment by BoschSensortec** [comment]
@xioTechnologies ,

This is fixed in the latest release.
