### ISSUE TITLE
Undefined static funtions in header

### ISSUE THREAD

**Issue by xioTechnologies** [BoschSensortec/BMI160_driver#3]
Please address the following compiler warnings:
```
../bmi160.h:11792:13: warning: 'xy1y2_to_xyz' declared 'static' but never defined
../bmi160.h:11841:36: warning: 'invalid_magnetic_field' declared 'static' but never defined
```

**Comment by BoschSensortec** [comment]
Thanks for your feedback.
Could you please provide the compiler which you are using  and also the compilation command details?

**Comment by xioTechnologies** [comment]
The warning is not specific to my use.  The code is clearly in error because it declares the functions with the static modifier in the header but without an implementation.  This makes no sense.

The functions in question are implemented in the .c file; also with a static modifier.  The intended purpose of the static modifier in this case is to restrict access to the function so that it may only be used in the .c file.

The solution is therefore to delete lines 11792 and 11841 in the header file.

For reference, I am only using the BMI160 driver in one project.  The compiler and command line arguments for this project are: "Microchip XC32 (V1.34)" with "-std=gnu99 -fgnu89-inline".
