### ISSUE TITLE
I am using Raspberry PI + BHI 160 shuttle board + BMM150,How to get data from sensors into Raspberry PI using any binary ? or Can I use same driver?

### ISSUE THREAD

**Issue by harshil1991** [BoschSensortec/BMI160_driver#33]
I am using Raspberry PI + BHI 160 shuttle board + BMM150, How to get data into Raspberry PI using binary.

Can I use this driver ?

**Comment by BoschSensortec** [comment]
Hi @harshil1991,

We will look into this and get back to you.

**Comment by BoschSensortec** [comment]
@harshil1991,

Moved issue currently over to the Bhy1 repository.  https://github.com/BoschSensortec/BHy1_driver_and_MCU_solution/issues/1
