### ISSUE TITLE
Incorrect argument documentation in comments

### ISSUE THREAD

**Issue by xioTechnologies** [BoschSensortec/BMI160_driver#5]
The argument  documentation for the "bmi160_set_output_enable" and "bmi160_get_output_enable" functions appear to be copy&pasted from the "bmi160_set_intr_output_type" function.

The argument descriptions and suggested values for "bmi160_set_output_enable" and "bmi160_get_output_enable"  are therefore incorrect.

**Comment by BoschSensortec** [comment]
BMI160 have one dedicated bit to enable the INT pin as output.  That is the reason we have this API interface.  It is not just copy&pasted from "bmi160_set_intr_output_type"

**Comment by xioTechnologies** [comment]
I am certain that the documentation is in error.

The documentation currently indicates that the first argument values for `bmi160_set_output_enable` are:
`BMI160_INTR1_OUTPUT_TYPE`
`BMI160_INTR2_OUTPUT_TYPE`
...and the second argument values are:
`BMI160_INPUT`
`BMI160_OUTPUT`

However, these are the arguments for `bmi160_set_intr_output_type`.  I believe that the correct arguments values for `bmi160_set_output_enable` are:
`BMI160_INTR1_OUTPUT_ENABLE`
`BMI160_INTR2_OUTPUT_ENABLE`
...and the second argument values are:
`BMI160_ENABLE`
`BMI160_DISABLE` 

The definitions `BMI160_INTR1_OUTPUT_ENABLE` and `BMI160_INTR2_OUTPUT_ENABLE` do not currently appear anywhere in the documentation!

The current documentation would result in the following code and commented behavior:
```
bmi160_set_output_enable(BMI160_INTR1_OUTPUT_TYPE, BMI160_INPUT); // output enabled

bmi160_set_output_enable(BMI160_INTR1_OUTPUT_TYPE, BMI160_OUTPUT); // output disabled
```

This is clearly incorrect!  It does not make sense that setting the 'output enable' to 'input' results in the output being enabled; and setting the 'output enable' to 'output' results in the output being disabled.  And it makes no sense that the first argument is `BMI160_INTR1_OUTPUT_TYPE` when there exists the definition `BMI160_INTR1_OUTPUT_ENABLE`.

The correct documentation, as I have suggested, would result in the following code and commented behavior:
```
bmi160_set_output_enable(BMI160_INTR1_OUTPUT_ENABLE, BMI160_ENABLE); // output enabled

bmi160_set_output_enable(BMI160_INTR1_OUTPUT_ENABLE, BMI160_DISABLE); // output disabled
```

**Comment by xioTechnologies** [comment]
The latest version of the driver has fixed the error in the documentation of the seconds argument but the documentation of the first argument still remains.

Just look at the switch statement cases for the first argument; it matches my suggested corrections and not the current documentation.

**Comment by BoschSensortec** [comment]
Thanks for your feedback, We will address this in upcoming releases.
