### ISSUE TITLE
About detecting single/double tapping

### ISSUE THREAD

**Issue by TatsuyaOoka** [BoschSensortec/BMI160_driver#59]
I am implementing a application detecting single/double tapping using BMI160 now.
Interrupt is fired and bits in INT_STATUS[2] are set along with tapping direction but INT_STATUS[0] is always 0x00.
I want to distinct both single/double tapping with s_tap_int/d_tap_int in INT_STATUS[0].
Registers related with tapping are set as below.

INT_MAP_0 -> 0x30
INT_EN_0 -> 0x30
INT_TAP_0 -> 0xC1
INT_TAP_1 -> 0x02
INT_OUT_CTRL -> 0x09
INT_LATCH -> 0x00

Why INT_STATUS[0] is always 0x00 ?
Could you tell me any points I have to check ?

**Comment by BoschSensortec** [comment]
Hi @TatsuyaOoka,

Are you using the driver within this repository? If so, can you share the snippets of code you are using the configure the sensor and subsequently read the interrupts status?

Thank you.

**Comment by TatsuyaOoka** [comment]
Hi, thanks for your reply.

I'm not using the driver code in the repository.

I set registers related tapping as below in initialize process and wait interrupt.
Interrupts other than tapping are not enabled.

bmi160_putreg8(BMI160_INTR_MAP_0, 0x30);
up_mdelay(1);
bmi160_putreg8(BMI160_INTR_ENABLE_0, 0x30);
up_mdelay(1);
bmi160_putreg8(BMI160_INTR_TAP_0, 0xC1);
up_mdelay(1);
bmi160_putreg8(BMI160_INTR_TAP_1, 0x02);
up_mdelay(1);
bmi160_putreg8(BMI160_INTR_OUT_CTRL, 0x09);
up_mdelay(1);
bmi160_putreg8(BMI160_INTR_LATCH, 0x00);
up_mdelay(1);

At same time, get accel data 768byte per 1 sec from DATA_14-19 as polling.
I get the value of INT_STATUS within 10ms from Interrupt is fired.
The value is like below.

INT_STATUS: [0]0x00, [1]0x00, [2]0xC0 //z-axis - tap
INT_STATUS: [0]0x00, [1]0x00, [2]0x10 //x-axis + tap
INT_STATUS: [0]0x00, [1]0x00, [2]0xA0 //y-axis - tap

Is there any possibility INT_STATUS[0] returns to 0x00 soon due to INT_LATCH is 0x00 ?
If so, why only INT_STATUS[2] keeps the value ?

BR

**Comment by BoschSensortec** [comment]
Hi @TatsuyaOoka,

For non-driver related issues and queries, please use our [contact form](https://www.bosch-sensortec.com/bst/contact/contact_form/contact_form).

**Comment by TatsuyaOoka** [comment]
Hi 

I submitted same issue to that form yesterday.
OK, I will wait for the reply.
Thanks for your cooperation.

BR
