### ISSUE TITLE
Sensor setting problem.

### ISSUE THREAD

**Issue by alextran1502** [BoschSensortec/BMI160_driver#61]
Hello, 

When I tried to change the range of accelerometer from 2G, 4G, 8G, 16G. I don't see any changes in the raw  output value getting from `get_accel_data` 1G is always at ~17900.

I did some digging and found out the function `rslt = bmi160_get_regs(BMI160_ACCEL_DATA_ADDR, data_array, 6 + len, dev);` in `get_accel_data` only read data register `0x12` which according to data sheet is **ACC_X<7:0> LSB.** Does that means the data that are parse in function `bmi160_get_regs` only belong to **x axis**?

Thanks,
Alex

**Comment by alextran1502** [comment]
Hi @BoschSensortec 

Thanks for the explanation.
I just wan to clarify that in the function `int8_t bmi160_get_regs(uint8_t reg_addr, uint8_t *data, uint16_t len, const struct bmi160_dev *dev)`, the `len` will determine how many register address is read after the `reg_addr`, correct?

**Comment by BoschSensortec** [comment]
Hi @alextran1502,

The `len` parameter determines how many registers are read including `reg_addr`.
