### ISSUE TITLE
.burst_read unset in sample example

### ISSUE THREAD

**Issue by cg666** [BoschSensortec/BMI160_driver#7]
Hi,

When INCLUDE_BMI160API is defined, i2c_routine() : 
- this function does not compile : struct_bmi160 shall be replaced by s_bmi160 (same for spi_routine)
- s_bmi160.burst_read = bmi160_i2c_bus_readBurst; is not set

Hope it will help.

**Comment by BoschSensortec** [comment]
Hi @cg666 ,

This is fixed in the latest release.
