### ISSUE TITLE
bmi160_set_accel_output_data_rate and bmi160_set_accel_bw() contradictory?

### ISSUE THREAD

**Issue by apiascik** [BoschSensortec/BMI160_driver#7]
Looking at bmi160.c, the function comment for `bmi160_set_accel_output_data_rate() ` lists the following possible values for the parameter `v_accel_bw_u8`:

```
*  @param  v_accel_bw_u8 :The value of accel selected accel bandwidth
 *  value |  output data rate
 * -------|--------------------------
 *    0   |  BMI160_ACCEL_OSR4_AVG1
 *    1   |  BMI160_ACCEL_OSR2_AVG2
 *    2   |  BMI160_ACCEL_NORMAL_AVG4
 *    3   |  BMI160_ACCEL_CIC_AVG8
 *    4   |  BMI160_ACCEL_RES_AVG2
 *    5   |  BMI160_ACCEL_RES_AVG4
 *    6   |  BMI160_ACCEL_RES_AVG8
 *    7   |  BMI160_ACCEL_RES_AVG16
 *    8   |  BMI160_ACCEL_RES_AVG32
 *    9   |  BMI160_ACCEL_RES_AVG64
 *    10  |  BMI160_ACCEL_RES_AVG128

```
The implementation seems to match this. However, when looking at `bmi160_set_accel_bw()` the function comment lists two sets of values, those for filter and under-sampling:

```
*	@note Filter configuration
 *  accel_us  | Filter configuration
 * -----------|---------------------
 *    0x00    |  OSR4 mode
 *    0x01    |  OSR2 mode
 *    0x02    |  normal mode
 *    0x03    |  CIC mode
 *    0x04    |  Reserved
 *    0x05    |  Reserved
 *    0x06    |  Reserved
 *    0x07    |  Reserved
 *
 *	@note accel under sampling mode
 *  accel_us  | Under sampling mode
 * -----------|---------------------
 *    0x00    |  no averaging
 *    0x01    |  average 2 samples
 *    0x02    |  average 4 samples
 *    0x03    |  average 8 samples
 *    0x04    |  average 16 samples
 *    0x05    |  average 32 samples
 *    0x06    |  average 64 samples
 *    0x07    |  average 128 samples
```

Also, see `#define BMI160_MAX_ACCEL_BW                 (7)` in bmi160.h

On inspection, the first method appears to interpret whether under-sampling mode should be enabled based on the bandwidth parameter (>= or < `BMI160_ACCEL_RES_AVG2`), while the second seems to indicate the interpretation of the bandwidth value is based on the under-sampling mode.

Please let me know if I'm just missing something.

**Comment by BoschSensortec** [comment]
Thanks for your feedback. We will change the comments for better understanding in the next version.

**Comment by BoschSensortec** [comment]
Hi, In bmi160_set_accel_bw  function, you can see the comments as below.
@note Accel bandwidth depends on under sampling parameter 
 @note under sampling parameter can be set by the function * "BMI160_SET_ACCEL_UNDER_SAMPLING_PARAMETER"
So user has to set the accel bandwidth and undersampling according to the table mentioned in the comments.
